# Generated by Django 3.1.12 on 2026-03-20 15:23

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djongo.models.fields
import travel.models.place


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('OWNER', 'Owner'), ('USER', 'User')], default='USER', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên hiển thị (vd: Vinpearl Land)', max_length=255)),
                ('search_name', models.CharField(help_text='vd: vinpearl land', max_length=255)),
                ('coordinate', djongo.models.fields.JSONField(default=dict)),
                ('is_city', models.BooleanField(default=True)),
                ('suggested_radius', models.IntegerField(default=5000)),
            ],
            options={
                'verbose_name': 'Địa điểm hệ thống',
            },
        ),
        migrations.CreateModel(
            name='TravelInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('num_people', models.IntegerField(default=1)),
                ('area', models.IntegerField()),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=24, null=True)),
                ('travel_style', models.IntegerField(blank=True, null=True)),
                ('food_type', models.IntegerField(blank=True, null=True)),
                ('accommodation_type', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_id', models.CharField(max_length=100, verbose_name='ID Input gốc')),
                ('summary_info', djongo.models.fields.JSONField(default=dict, verbose_name='Thông tin tổng kết')),
                ('itinerary', djongo.models.fields.JSONField(default=list, verbose_name='Lịch trình chi tiết')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_outputs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kết quả lịch trình',
                'verbose_name_plural': 'Danh sách kết quả',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, help_text='Thông tin chi tiết')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', djongo.models.fields.JSONField(default=dict)),
                ('off_weekdays', djongo.models.fields.JSONField(default=list)),
                ('off_dates', djongo.models.fields.JSONField(default=list)),
                ('active_hours', djongo.models.fields.JSONField(default=list)),
                ('price_level', models.IntegerField(default=1)),
                ('min_price', models.FloatField(blank=True, null=True)),
                ('max_price', models.FloatField(blank=True, null=True)),
                ('has_surge_price', models.BooleanField(default=False, help_text='Có tăng giá cuối tuần/lễ không')),
                ('discounts', djongo.models.fields.ArrayField(blank=True, default=list, model_container=travel.models.place.Discount)),
                ('priority', models.IntegerField(default=0)),
                ('review_count', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0, help_text='Điểm đánh giá trung bình từ 0 đến 5')),
                ('rating_bucket', models.IntegerField(default=0)),
                ('comments', djongo.models.fields.ArrayField(blank=True, default=list, model_container=travel.models.place.Comment)),
                ('cuisine_types', djongo.models.fields.JSONField(blank=True, default=list)),
                ('dishes', djongo.models.fields.ArrayField(blank=True, default=list, model_container=travel.models.place.Dish)),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurant/')),
                ('owner', models.OneToOneField(blank=True, limit_choices_to={'role': 'OWNER'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_restaurant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, help_text='Thông tin chi tiết')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', djongo.models.fields.JSONField(default=dict)),
                ('off_weekdays', djongo.models.fields.JSONField(default=list)),
                ('off_dates', djongo.models.fields.JSONField(default=list)),
                ('active_hours', djongo.models.fields.JSONField(default=list)),
                ('price_level', models.IntegerField(default=1)),
                ('min_price', models.FloatField(blank=True, null=True)),
                ('max_price', models.FloatField(blank=True, null=True)),
                ('has_surge_price', models.BooleanField(default=False, help_text='Có tăng giá cuối tuần/lễ không')),
                ('discounts', djongo.models.fields.ArrayField(blank=True, default=list, model_container=travel.models.place.Discount)),
                ('priority', models.IntegerField(default=0)),
                ('review_count', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0, help_text='Điểm đánh giá trung bình từ 0 đến 5')),
                ('rating_bucket', models.IntegerField(default=0)),
                ('comments', djongo.models.fields.ArrayField(blank=True, default=list, model_container=travel.models.place.Comment)),
                ('hotel_type', models.IntegerField()),
                ('room_types', djongo.models.fields.ArrayField(blank=True, default=list, model_container=travel.models.place.RoomTypePrice)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotel/')),
                ('owner', models.OneToOneField(blank=True, limit_choices_to={'role': 'OWNER'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_hotel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, help_text='Thông tin chi tiết')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', djongo.models.fields.JSONField(default=dict)),
                ('off_weekdays', djongo.models.fields.JSONField(default=list)),
                ('off_dates', djongo.models.fields.JSONField(default=list)),
                ('active_hours', djongo.models.fields.JSONField(default=list)),
                ('price_level', models.IntegerField(default=1)),
                ('min_price', models.FloatField(blank=True, null=True)),
                ('max_price', models.FloatField(blank=True, null=True)),
                ('has_surge_price', models.BooleanField(default=False, help_text='Có tăng giá cuối tuần/lễ không')),
                ('discounts', djongo.models.fields.ArrayField(blank=True, default=list, model_container=travel.models.place.Discount)),
                ('priority', models.IntegerField(default=0)),
                ('review_count', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0, help_text='Điểm đánh giá trung bình từ 0 đến 5')),
                ('rating_bucket', models.IntegerField(default=0)),
                ('comments', djongo.models.fields.ArrayField(blank=True, default=list, model_container=travel.models.place.Comment)),
                ('tags', djongo.models.fields.JSONField(blank=True, default=list)),
                ('image', models.ImageField(blank=True, null=True, upload_to='attraction/')),
                ('owner', models.OneToOneField(blank=True, limit_choices_to={'role': 'OWNER'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_attraction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='traveloutput',
            index=models.Index(fields=['input_id'], name='travel_trav_input_i_999286_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['-rating_bucket', '-priority', 'price_level'], name='travel_rest_rating__12228a_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['-rating_bucket', '-priority', 'price_level'], name='travel_hote_rating__2ce1e9_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['hotel_type', '-rating_bucket', '-priority', 'price_level'], name='travel_hote_hotel_t_d5a039_idx'),
        ),
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['-rating_bucket', '-priority', 'price_level'], name='travel_attr_rating__dd4b4d_idx'),
        ),
    ]
