# Generated by Django 3.1.12 on 2026-03-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['search_name'], name='idx_location_search_name'),
        ),
    ]
