# Generated by Django 3.1.12 on 2026-04-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20260320_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_location',
            field=models.CharField(choices=[('RESTAURANT', 'Nhà hàng'), ('ACCOMMODATION', 'Nơi ở (Khách sạn/Homestay)'), ('ENTERTAINMENT', 'Khu vui chơi'), ('NONE', 'Không có')], default='NONE', max_length=20),
        ),
    ]
