# Generated by Django 3.1.12 on 2026-04-17 15:26

from django.db import migrations
import djongo.models.fields
import travel.models.place


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_auto_20260417_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='active_hours',
            field=djongo.models.fields.JSONField(default=travel.models.place.get_default_list),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='comments',
            field=djongo.models.fields.ArrayField(blank=True, default=travel.models.place.get_default_list, model_container=travel.models.place.Comment),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='discounts',
            field=djongo.models.fields.ArrayField(blank=True, default=travel.models.place.get_default_list, model_container=travel.models.place.Discount),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='location',
            field=djongo.models.fields.JSONField(blank=True, default=travel.models.place.get_default_location),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='off_dates',
            field=djongo.models.fields.JSONField(default=travel.models.place.get_default_list),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='off_weekdays',
            field=djongo.models.fields.JSONField(default=travel.models.place.get_default_list),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='tags',
            field=djongo.models.fields.JSONField(blank=True, default=travel.models.place.get_default_list),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='active_hours',
            field=djongo.models.fields.JSONField(default=travel.models.place.get_default_list),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='comments',
            field=djongo.models.fields.ArrayField(blank=True, default=travel.models.place.get_default_list, model_container=travel.models.place.Comment),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='discounts',
            field=djongo.models.fields.ArrayField(blank=True, default=travel.models.place.get_default_list, model_container=travel.models.place.Discount),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=djongo.models.fields.JSONField(blank=True, default=travel.models.place.get_default_location),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='off_dates',
            field=djongo.models.fields.JSONField(default=travel.models.place.get_default_list),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='off_weekdays',
            field=djongo.models.fields.JSONField(default=travel.models.place.get_default_list),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='room_types',
            field=djongo.models.fields.ArrayField(blank=True, default=travel.models.place.get_default_list, model_container=travel.models.place.RoomTypePrice),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='active_hours',
            field=djongo.models.fields.JSONField(default=travel.models.place.get_default_list),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='comments',
            field=djongo.models.fields.ArrayField(blank=True, default=travel.models.place.get_default_list, model_container=travel.models.place.Comment),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine_types',
            field=djongo.models.fields.JSONField(blank=True, default=travel.models.place.get_default_list),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='discounts',
            field=djongo.models.fields.ArrayField(blank=True, default=travel.models.place.get_default_list, model_container=travel.models.place.Discount),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='dishes',
            field=djongo.models.fields.ArrayField(blank=True, default=travel.models.place.get_default_list, model_container=travel.models.place.Dish),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=djongo.models.fields.JSONField(blank=True, default=travel.models.place.get_default_location),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='off_dates',
            field=djongo.models.fields.JSONField(default=travel.models.place.get_default_list),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='off_weekdays',
            field=djongo.models.fields.JSONField(default=travel.models.place.get_default_list),
        ),
    ]
