# Generated by Django 3.1.12 on 2026-04-17 15:36

from django.db import migrations
import djongo.models.fields
import travel.models.place


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_auto_20260417_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='comments',
            field=djongo.models.fields.ArrayField(blank=True, default=[], model_container=travel.models.place.Comment),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='discounts',
            field=djongo.models.fields.ArrayField(blank=True, default=[], model_container=travel.models.place.Discount),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='comments',
            field=djongo.models.fields.ArrayField(blank=True, default=[], model_container=travel.models.place.Comment),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='discounts',
            field=djongo.models.fields.ArrayField(blank=True, default=[], model_container=travel.models.place.Discount),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='room_types',
            field=djongo.models.fields.ArrayField(blank=True, default=[], model_container=travel.models.place.RoomTypePrice),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='comments',
            field=djongo.models.fields.ArrayField(blank=True, default=[], model_container=travel.models.place.Comment),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='discounts',
            field=djongo.models.fields.ArrayField(blank=True, default=[], model_container=travel.models.place.Discount),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='dishes',
            field=djongo.models.fields.ArrayField(blank=True, default=[], model_container=travel.models.place.Dish),
        ),
    ]
