# Generated by Django 3.1.12 on 2026-04-23 16:14

from django.db import migrations, models
import djongo.models.fields
import travel.models.trip


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_auto_20260418_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelinput',
            name='percentage_attraction',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='travelinput',
            name='percentage_hotel',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='travelinput',
            name='percentage_restaurant',
            field=models.IntegerField(default=35),
        ),
        migrations.AlterField(
            model_name='location',
            name='coordinate',
            field=djongo.models.fields.JSONField(blank=True, default=travel.models.trip.default_dict),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_city',
            field=models.BooleanField(blank=True, default=travel.models.trip.default_list),
        ),
        migrations.AlterField(
            model_name='travelinput',
            name='accommodation_type',
            field=djongo.models.fields.JSONField(blank=True, default=travel.models.trip.default_list),
        ),
        migrations.AlterField(
            model_name='travelinput',
            name='food_type',
            field=djongo.models.fields.JSONField(blank=True, default=travel.models.trip.default_list),
        ),
        migrations.AlterField(
            model_name='travelinput',
            name='travel_style',
            field=djongo.models.fields.JSONField(blank=True, default=travel.models.trip.default_list),
        ),
        migrations.AlterField(
            model_name='traveloutput',
            name='itinerary',
            field=djongo.models.fields.JSONField(blank=True, default=travel.models.trip.default_list, verbose_name='Lịch trình chi tiết'),
        ),
        migrations.AlterField(
            model_name='traveloutput',
            name='summary_info',
            field=djongo.models.fields.JSONField(blank=True, default=travel.models.trip.default_dict, verbose_name='Thông tin tổng kết'),
        ),
    ]
